services:
  - type: web
    name: nhentai-bot
    env: python
    region: frankfurt  # Лучший регион для EU
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: your_bot_token_here
      - key: ADMIN_ID
        value: "YOUR_TELEGRAM_ID"
      - key: WHITEL
